Fixing missing debug flag
deep-entertainment/godottpd pull request #11
Opened 2023-10-23 23:10 UTC by JDDoesDev

The debug flag was removed in a previous commit.  Adding back to prevent having debug info all the time.

2023-11-03 07:42 UTC, dploeger requested changes
Thanks for sending this. Could you please check out my finding and also rewrite your commit message to include a 

fix:

prefix before it? I'm using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) here

2023-11-03 07:42 UTC, dploeger commented on addons/godottpd/http_server.gd
> +	if _logger:
```suggestion
	if _logging:
```

Shouldn't this be logging?

2024-05-02 17:25 UTC, Anutrix commented
What's the status on this?

2024-05-02 17:33 UTC, dploeger commented
@JDDoesDev  can you check out my requested changes please?

2024-08-19 13:07 UTC, dploeger commented
Hey, @JDDoesDev. Can you please take a look at this?

2024-12-18 08:42 UTC, dploeger commented
Closing this for the time being

2024-12-18 08:42 UTC, closed without merging