Updated comments to allow documentation viewing in godot
deep-entertainment/godottpd pull request #15
Opened 2024-11-01 11:54 UTC by dragmine149

Changed comments to allow for viewing the documentation in godot on all main functions at least.
Functions beginning with `_` comments were kept the same.

All functions that were changed kept most of the documentation although expanded in some cases. (Fell free to revert this). Main cases being the `HttpRouter` class and `HttpServer.enable_cors()`

Please at least check my documentation for `HttpServer.enable_cors()` as there wasn't any documentation for it and i'm not 100% sure on how it works. (Although it just felt wrong to have no documentation so i included something)

2024-12-10 19:12 UTC, dploeger requested changes
This is really great work! Thanks a lot.

You got the CORS stuff right and I know it's hard. I had a hard time studying it as well. 😄

Just a few remarks and we're set I guess. And could I also ask you to change the commit messages? I'm using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) here. So your commits should start with something like "feat:" or "fix:".

Thanks a lot for your work!

2024-12-10 19:12 UTC, dploeger commented on addons/godottpd/http_request.gd
> +# #Override `str()` method, automatically called in `print()` function
```suggestion
## Override `str()` method, automatically called in `print()` function
```

2024-12-10 19:12 UTC, dploeger commented on addons/godottpd/http_server.gd
> +## Controlls a back-end localhost server.
I'd rather go with

```suggestion
## Provides a web server with routes for specific endpoints
```

2024-12-10 19:12 UTC, dploeger commented on addons/godottpd/http_server.gd
> +## [br][param allowed_origins] - The origins that area allowed to be access from this sesrver
```suggestion
## [br][param allowed_origins] - The origins that are allowed to be accessed from this server
```

2024-12-10 19:12 UTC, dploeger commented on addons/godottpd/http_server.gd
> +## [br][param access_control_allowed_methods] - The methods that are allowed to be sent
```suggestion
## [br][param access_control_allowed_methods] - The methods that are allowed to be used
```

2024-12-11 17:27 UTC, dragmine149 commented
Updated the title (Please don't mind the multiple attempts) and approved of the requests.

2024-12-11 19:18 UTC, dploeger commented
Thanks but I rather talked about changing the commit messages. You can do that using an interactive rebase and reword the commits.

If you don't know how, though, don't worry. I can also simply squash the PR into a single commit that matches the conventional commit message.

2024-12-14 19:47 UTC, dragmine149 commented
Took me a while to figure out how the interactive rebase worked but got it sorted, and as such updated the commit messages.

2024-12-14 20:01 UTC, dploeger approved these changes
Awesome! Thanks a lot. 🎁

2024-12-14 20:01 UTC, merged

2024-12-14 20:02 UTC, dploeger commented
I think I'll release a new version tomorrow as I'm currently only on mobile.