fix: use carriage returns in response
deep-entertainment/godottpd pull request #7
Opened 2022-10-03 00:18 UTC by monitz87

The HTTP 1.1 standard requires header fields (and blank lines) to be terminated in CRLF (\r\n). Some http request libraries have taken this to heart and throw errors when this is not the case, or require a special flag to bypass the issue. Reference: https://www.rfc-editor.org/rfc/rfc2616#section-2.2

Examples of libraries that enforce this in node.js: axios, http

DISCLAIMER: I have only tested this in OSX. I imagine it *_should_* be system agnostic, but this should be verified before merging. I will try to test it in linux as well, but I don't have access (or the inclination to get access) to a windows box

Great job btw, the addon is super simple and elegant. My use case was fairly complex and this addon made my life so much easier, so kudos to the team

2022-10-03 07:18 UTC, dploeger requested changes
Thanks a lot. Just a very small change requested and we're ready to merge.

2022-10-03 07:18 UTC, dploeger commented on addons/godottpd/http_response.gd
> +	client.put_data("Connection: close\r\n".to_scii())
There's a typo here, right? Should be to_ascii.

2022-10-03 13:17 UTC, monitz87 commented on addons/godottpd/http_response.gd
> +	client.put_data("Connection: close\r\n".to_scii())
Yeah, idk how that happened. I'll fix it right away

2022-10-03 14:27 UTC, merged

2022-10-03 14:28 UTC, dploeger commented
Great. Thanks. 🎁 

I will release this in a few days.

2022-10-04 15:12 UTC, dploeger commented
Released as 0.3.0